#!/bin/bash

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

if [ -z "$FILES" ]; then
    exit 0
fi

for file in $FILES; do
    yapf -i "$file"
    git add "$file"
done

exit 0

